# Generated by Django 5.2.7 on 2025-10-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
