# Generated by Django 5.2.7 on 2025-11-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency_from',
            field=models.CharField(choices=[('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('TZS', 'Tanzanian Shilling'), ('RWF', 'Rwandan Franc'), ('BIF', 'Burundi Franc'), ('ZAR', 'South African Rand'), ('USD', 'US Dollar'), ('GBP', 'British Pound'), ('EUR', 'Euro'), ('AED', 'UAE Dirham'), ('SAR', 'Saudi Riyal'), ('EGP', 'Egyptian Pound'), ('NGN', 'Nigerian Naira')], default='KES', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency_to',
            field=models.CharField(choices=[('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('TZS', 'Tanzanian Shilling'), ('RWF', 'Rwandan Franc'), ('BIF', 'Burundi Franc'), ('ZAR', 'South African Rand'), ('USD', 'US Dollar'), ('GBP', 'British Pound'), ('EUR', 'Euro'), ('AED', 'UAE Dirham'), ('SAR', 'Saudi Riyal'), ('EGP', 'Egyptian Pound'), ('NGN', 'Nigerian Naira')], default='KES', max_length=3),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('TZS', 'Tanzanian Shilling'), ('RWF', 'Rwandan Franc'), ('BIF', 'Burundi Franc'), ('ZAR', 'South African Rand'), ('USD', 'US Dollar'), ('GBP', 'British Pound'), ('EUR', 'Euro'), ('AED', 'UAE Dirham'), ('SAR', 'Saudi Riyal'), ('EGP', 'Egyptian Pound'), ('NGN', 'Nigerian Naira')], default='KES', max_length=3),
        ),
    ]
