# Generated by Django 5.2.7 on 2025-11-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_transaction_currency_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pin',
            field=models.CharField(blank=True, help_text='Hashed 6-digit PIN for transfers', max_length=128, null=True),
        ),
    ]
